### ISSUE TITLE
List of shops screen

### ISSUE THREAD

**Issue by Niyaz-ik** [Uber-coffee/Mobile-app#14]
**Tasks**
- [x] https://github.com/Uber-coffee/Mobile-app/issues/43
- [x] https://github.com/Uber-coffee/Mobile-app/issues/50
- [x] https://github.com/Uber-coffee/Mobile-app/issues/51

**Description**
AS A user I WANT TO have an ability to choose a coffee shop from a list of several shops SO THAT I can order from the shop what I want.

**Acceptance criteria**
1. The screen must contain list of shops, 2 buttons at the bottom of the page (List of shops, Profile), button for filtering in upper right corner.
2. User can scroll down and select other shops.
3. The user can tap on one of the coffee shop and go to the menu screen shop.
4. The user can tap on Profile button and go to the Profile screen.
5. The user can see name of the application.
6. The following criteria should be in the coffee shop card: 
a. The user can see minimum price.
b. The user can see minimum waiting time for order.
c. The user can see average score of the coffee shop.
d. The user can see address of the coffee shop.
e. The user can see distance between user and coffee shop.
f. Colored icon of circle should represent functioning capacity of coffee shop: green circle is the sign of available shop; 
yellow - busy but able to take orders; red - not recommended for visit right now.
7. If the user tap on button for filtering, dialog window for choosing filters should be shown:
a. Two buttons must contain - "Enter" and "Reset": first one to apply filters and second to reset visual signs of selected buttons.
b. Filter shops by distance: up to 0.5/1.0/1.5 km.
c. Filter by congestion of the shop: green/yellow/red circle.

![image](https://user-images.githubusercontent.com/55930922/87138747-52f85980-c2b8-11ea-9eab-6b61b7881255.png)
