### ISSUE TITLE
Order screen

### ISSUE THREAD

**Issue by Niyaz-ik** [Uber-coffee/Mobile-app#56]
**Tasks**

- [x] https://github.com/Uber-coffee/Mobile-app/issues/53

- [x] https://github.com/Uber-coffee/Mobile-app/issues/69

- [ ] https://github.com/Uber-coffee/Mobile-app/issues/81

**Description**
AS A user I WANT TO check all positions in my order with additional information SO THAT I can edit my choice and then confirm it.

**Acceptance criteria**
1. The screen must contain information about user's order: time of waiting order (specifically it is time for which user must arrive to the coffee shop - in N mins coffee will wait him), cards with beverages and buttons with bin to delete corresponding position, information about total cost and button for submission.
2. User can scroll down the list with positions in the order.
3. Each card must contain following information:
a.  Name of drink in the order.
b. Chosen size of beverage.
c. Price for this size.
d. Quantity of portions of this drink with 2 buttons for regulating it: "+" and "-". 
4. Total cost should be dynamically changed with changing in quantity.
5. User can click on button "Submit" and go to the screen with timer.

![image](https://user-images.githubusercontent.com/55836255/87281197-a60e1e80-c4fb-11ea-8934-6e23b244969f.png)
![image](https://user-images.githubusercontent.com/55836255/87282767-444eb400-c4fd-11ea-840a-47d086f15f8a.png)
